travis:
  secure:
    BINSTAR_TOKEN: eHGtbya6U79tWbNIoORE0FJ49lHG6AHivEN86YRh9KHSF2jcL0/Bbj8pm+tkCi+p+9FZe9it+0d7NBv5lcj8LqF8tX9Gn+dK46o8cLaw9iuNV53OM7QN+APju7yurwawACOa2CN4Q6CptKguvh39wYinn91mteJHar03aAuoVi6C9tQBPQizvg7XDlccrH32PfF97E2rWc+nieOqT+xNVJTaPmblzplQteAsSTGLgynjuR6edeLhjZIppfymg9NFc72eGZX+8gYzXnJrTYQAnLsGYjyVqBPf4HwhK9mfCTi0ogtR5UNuo1Q0bBiX+L/4CsMrKT/PaN7zYl0YmX5kd9Xo/mRgcxP4lPhlhp28u3C3rCgDe6rwa88GwqHw4nIlmEmTDIoBuPDlpjGWkK2Ab1QUw39Wch8Ni9JjX89sSr6ImEnjK0y32AB21U7swa6EqSVcJ2QDToDyTANiSMs5wuS9yr7PGvscfeE6Ec7Cr2gTOSSxG6yO9qJnaZA4nqkfKSz0AyLJ49+q9rQzGz9FRknunWX4VC5Bw28IE2R1gr76YCcAhCDKYWmj+qDdN99Ib+iOdKyXE8DOsq9bXdFwpKlDmBoKTmNjLY+06lWygE0oaNJji3t2Ne70TcQk1Bj240Q09XwtkZKKA3pYztLmit36c41qkEBvQP8eZVoLQOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
